title: Documentation Site for the TREN Application
description: See also corpus made by using TREN: https://bostanberkay.github.io/turkish-english-intraword-code-switching-corpus/
theme: jekyll-theme-slate
